"""add_llm_calls_count_users_table

Revision ID: a009eedda8d3
Revises: bda28ec2e146
Create Date: 2026-04-11 14:26:18.273017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a009eedda8d3'
down_revision: Union[str, Sequence[str], None] = 'bda28ec2e146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('llm_calls_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'llm_calls_count')
    # ### end Alembic commands ###
